## Data Mining Lab
## Name = Atul Sharma
## Enrollment No.- 2018IMSCS015
## Question Code- 3 (Implementation of Apriori)

In [1]:
# importing libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
#importing the dataset
# Using G.CSV of old assignment for this project
data = pd.read_csv('C:\Drive_B\CURAJ\Sem 9\DATA Mining lab\programs\data\G.csv')
data.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#finding the shape of data that we are using
data.shape

(9835, 33)

In [7]:
data.values[2,2]

nan

In [8]:
# we have to import Association_rules and Apriori from mlxtend.frequent_patterns

In [10]:
#creating the transaction list for all the combination of the data
transact = []
for i in range(0, 5000):
  transact.append([str(data.values[i,j]) for j in range(1, 33)])

In [17]:
from apyori import apriori
Rule= apriori(transactions = transact, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)
Rule

In [19]:
Results = list(Rule) 
def inspect(Results):
    left_hand  = [tuple(result[2][0][0])[0] for result in Results]
    right_hand = [tuple(result[2][0][1])[0] for result in Results]
    support    = [result[1] for result in Results]
    confidence = [result[2][0][2] for result in Results]
    lift       = [result[2][0][3] for result in Results]
    return list(zip(left_hand, right_hand, support, confidence, lift))
result = pd.DataFrame(inspect(Results), columns = ['Left_Hand_Side', 'Right_Hand_Side', 'Support', 'Confidence', 'Lift'])

In [20]:
result.nlargest(n = 10, columns = 'Lift')

      Left_Hand_Side     Right_Hand_Side  Support  Confidence      Lift
9              flour               sugar   0.0054    0.296703  8.106647
15  processed cheese         white bread   0.0048    0.315789  7.483163
1      baking powder               sugar   0.0048    0.250000  6.830601
13               ham         white bread   0.0054    0.204545  4.847049
4             liquor        bottled beer   0.0042    0.396226  4.716981
2      baking powder  whipped/sour cream   0.0064    0.333333  4.385965
8              flour           margarine   0.0046    0.252747  3.999165
14     roll products           margarine   0.0030    0.250000  3.955696
11           mustard         frankfurter   0.0032    0.242424  3.935458
3            berries  whipped/sour cream   0.0088    0.287582  3.783970